#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_control_flow_attributes : require

#include "common/random.glsl"
#include "common/ray.glsl"
#include "common/sphere.glsl"
#include "common/triangle.glsl"
#include "common/bvh.glsl"
#include "common/color.glsl"
#include "common/sampling.glsl"
#include "common/material.glsl"
#include "common/debug.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba8) uniform image2D outputImage;

layout(set = 0, binding = 1, rgba16f) uniform image2D accumulatedImage;

layout(std430, set = 0, binding = 2)
readonly buffer SphereBuffer {
    Sphere spheres[];
};

layout(std430, set = 0, binding = 3)
readonly buffer TriangleBuffer {
    Triangle triangles[];
};

layout(std430, set = 0, binding = 4)
readonly buffer MaterialBuffer {
    Material materials[];
};

layout(std430, set = 0, binding = 5)
readonly buffer BvhBuffer {
    BVHNode nodes[];
};

layout(push_constant) uniform PushConstants {
    vec4 cameraPosition;
    vec4 pixelStart;
    vec4 pixelDU;
    vec4 pixelDV;

    vec4 defocusDiskU;
    vec4 defocusDiskV;

    uint sphereCnt;
    uint triangleCnt;
    uint samplesPerPixel;
    uint maxBounces;
    uint accumulatedFrames;
    uint accumulateRays;
    uint viewMode;
    uint BVHthreshold;
} pc;

const float FLOAT_MAX = 3.402823466e+38;

const uint VIEW_NORMAL = 0u;
const uint VIEW_BOX_TESTS = 3u;

bool hitBVH(
    Ray ray,
    float tMin,
    float tMax,
    out HitRecord closestHit,
    out uint boxTests
) {
    bool hitAnything = false;
    float closestT = tMax;

    boxTests = 0u;

    uint stack[MAX_DEPTH];
    uint stackPtr = 0;

    stack[stackPtr++] = 0;

    while (stackPtr > 0) {
        uint nodeIndex = stack[--stackPtr];

        BVHNode node = nodes[nodeIndex];

        float tNear;

        // We are about to perform an AABB test
        boxTests++;

        if (!hitAABB(
            ray,
            node.boundsMin,
            node.boundsMax,
            tMin,
            closestT,
            tNear
        )) {
            continue;
        }

        if (node.triangleCount > 0) {
            for (uint i = 0; i < node.triangleCount; ++i) {
                uint triangleIndex = node.firstTriangle + i;

                HitRecord temp;

                if (hitTriangleMoller(
                    ray,
                    triangles[triangleIndex],
                    tMin,
                    closestT,
                    temp
                )) {
                    hitAnything = true;
                    closestT = temp.t;
                    closestHit = temp;
                }
            }
        }
        else {
            stack[stackPtr++] = node.leftChild;
            stack[stackPtr++] = node.rightChild;
        }
    }

    return hitAnything;
}

uint getBVHBoxTests(Ray ray) {
    HitRecord rec;
    uint boxTests;

    hitBVH(
        ray,
        0.001,
        FLOAT_MAX,
        rec,
        boxTests
    );

    return boxTests;
}

bool hitGround(
    Ray ray,
    float tMin,
    float tMax,
    out HitRecord rec
) {
    const float groundY = -1.0;

    // ray is almost parallel to the ground
    if (abs(ray.direction.y) < 0.0001) {
        return false;
    }

    float t = (groundY - ray.origin.y) / ray.direction.y;

    // case 1: intersection lies behind the camera/ray origin
    // case 2: intersection is behind another object
    if (t <= tMin || t >= tMax) {
        return false;
    }

    rec.t = t;
    rec.position = rayAt(ray, t);

    vec3 outwardNormal = vec3(0.0, 1.0, 0.0);

    setFaceNormal(
        ray,
        outwardNormal,
        rec
    );

    rec.materialIndex = MATERIAL_GROUND;

    return true;
}

bool hitScene(
    Ray ray,
    out HitRecord closestHit
) {
    bool hitAnything = false;
    float closestT = FLOAT_MAX;

    // spheres
    for (uint i = 0; i < pc.sphereCnt; ++i) {
        HitRecord temp;

        if (hitSphere(ray, spheres[i], 0.001, closestT, temp)) {
            hitAnything = true;
            closestT = temp.t;
            closestHit = temp;
        }
    }

    // triangles
    HitRecord triangleHit;
    uint bvhBoxTests;

    if (
        hitBVH(
            ray,
            0.001,
            closestT,
            triangleHit,
            bvhBoxTests
        )
    ) {
        hitAnything = true;
        closestT = triangleHit.t;
        closestHit = triangleHit;
    }

    // ground
    HitRecord groundHit;

    if (
        hitGround(
            ray,
            0.001,
            closestT,
            groundHit
        )
    ) {
        hitAnything = true;
        closestT = groundHit.t;
        closestHit = groundHit;
    }

    return hitAnything;
}

// takes a ray plus RNG state and follows the ray through the scene
// as it bounces, returns the RGB contribution of the whole path.
vec3 rayColor(
    Ray ray,
    inout uint rngState
) {
    vec3 throughput = vec3(1.0);

    for (uint bounce = 0; bounce < pc.maxBounces; ++bounce) {
        HitRecord rec;

        if (hitScene(ray, rec)) {
            Material material = materials[rec.materialIndex];

            Ray scattered;
            vec3 attenuation;

            if (!scatter(
                ray,
                material,
                rec,
                rngState,
                scattered,
                attenuation
            )) {
                return vec3(0.0);
            }

            throughput *= attenuation;

            ray = scattered;
        }
        else {
            return throughput * skyColor(ray.direction);
        }
    }

    return vec3(0.0);
}


void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);

    if (pixel.x >= size.x || pixel.y >= size.y) {
        return;
    }

    // random jittered sampling for anti-aliasing
    // each pixel traces 8 rays instead of 1.

    // random number generator state
    // a unique id per pixel is used as the seed.
    uint pixelIdx = uint(pixel.y * size.x + pixel.x);
    uint rngState = tea(pixelIdx, pc.accumulatedFrames);

    vec3 color = vec3(0.0);

    if (pc.viewMode == VIEW_BOX_TESTS) {
        vec3 pixelPosition =
            pc.pixelStart.xyz
            + float(pixel.x) * pc.pixelDU.xyz
            + float(pixel.y) * pc.pixelDV.xyz;

        Ray ray;
        ray.origin = pc.cameraPosition.xyz;
        ray.direction = normalize(pixelPosition - ray.origin);

        uint boxTests = getBVHBoxTests(ray);

        vec3 debugColor = boxTestHeatmap(
            boxTests,
            pc.BVHthreshold
        );

        imageStore(outputImage, pixel, vec4(debugColor, 1.0));
        return;
    }

    for (uint i = 0; i < pc.samplesPerPixel; ++i) {
        // rnd(rngState) produces random number from [0,1] resulting 
        // range is [-0.5, 0.5] which shows the offset from the original pixel
        vec2 jitter = vec2(rnd(rngState), rnd(rngState)) - 0.5;

        // pc.pixelDU is the equivalent world space distance of moving one pixel
        vec3 pixelPosition =
            pc.pixelStart.xyz
            + (float(pixel.x) + jitter.x) * pc.pixelDU.xyz
            + (float(pixel.y) + jitter.y) * pc.pixelDV.xyz;

        Ray ray;

        // defocus blur
        vec2 diskSample = generateRandomInUnitDisk(rngState);
        vec3 lensOffset = 
            diskSample.x * pc.defocusDiskU.xyz +
            diskSample.y * pc.defocusDiskV.xyz;

        ray.origin = pc.cameraPosition.xyz + lensOffset;
        ray.direction = normalize(pixelPosition - ray.origin);

        color += rayColor(ray, rngState);
    }

    color /= float(pc.samplesPerPixel);

    vec3 displayColor = color;

    // accumulate rays toggled on
    if (pc.accumulateRays == 1u) {
        if (pc.accumulatedFrames == 0u) {
            imageStore(
                accumulatedImage, 
                pixel, 
                vec4(color, 1.0)
            );
        }
        else {
            vec3 prev = imageLoad(accumulatedImage, pixel).rgb;
            float n = float(pc.accumulatedFrames);
            vec3 accumulatedColor = (prev * n + color) / (n + 1.0);
            imageStore(
                accumulatedImage, 
                pixel, 
                vec4(accumulatedColor, 1.0)
            );
            displayColor = accumulatedColor;
        }   
    }

    // gamma correction
    displayColor = linearToGamma(displayColor);

    imageStore(outputImage, pixel, vec4(displayColor, 1.0));
}