#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_control_flow_attributes : require

#include "common/random.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba8) uniform image2D outputImage;

struct Sphere {
    vec4 centerRadius; // xyz = center, w = radius
    vec4 color;        // rgba
};

layout(std430, set = 0, binding = 1) readonly buffer SphereBuffer {
    Sphere spheres[];
};

layout(push_constant) uniform PushConstants {
    vec4 cameraPosition;
    vec4 pixelStart;
    vec4 pixelDU;
    vec4 pixelDV;

    uint objectCnt;
} pc;

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct HitRecord {
    vec3 position;
    vec3 normal;
    float t;
    bool frontFace;
    vec3 color;
};

vec3 sphereCenter(Sphere sphere) {
    return sphere.centerRadius.xyz;
}

float sphereRadius(Sphere sphere) {
    return sphere.centerRadius.w;
}

vec3 skyColor(vec3 direction) {
    float t = 0.5 * (direction.y + 1.0);
    return mix(
        vec3(1.0, 1.0, 1.0),
        vec3(0.5, 0.7, 1.0),
        t
    );
}

vec3 rayAt(Ray ray, float t) {
    return ray.origin + t * ray.direction;
}

void setFaceNormal(
    Ray ray,
    vec3 outwardNormal,
    inout HitRecord rec
) {
    rec.frontFace = dot(ray.direction, outwardNormal) < 0.0;
    rec.normal = rec.frontFace ? outwardNormal : -outwardNormal;
}

bool hitSphere(
    Ray ray,
    Sphere sphere,
    float tMin,
    float tMax,
    out HitRecord rec
) {
    vec3 center = sphereCenter(sphere);
    float radius = sphereRadius(sphere);

    vec3 oc = center - ray.origin;

    float a = dot(ray.direction, ray.direction);
    float h = dot(ray.direction, oc);
    float c = dot(oc, oc) - radius * radius;

    float discriminant = h * h - a * c;

    if (discriminant < 0.0) {
        return false;
    }

    float sqrtD = sqrt(discriminant);

    float root = (h - sqrtD) / a;
    if (root <= tMin || root >= tMax) {
        root = (h + sqrtD) / a;
        if (root <= tMin || root >= tMax) {
            return false;
        }
    }

    rec.t = root;
    rec.position = rayAt(ray, root);

    vec3 outwardNormal = (rec.position - center) / radius;
    setFaceNormal(ray, outwardNormal, rec);

    rec.color = sphere.color.rgb;

    return true;
}

bool hitGround(
    Ray ray,
    float tMin,
    float tMax,
    out HitRecord rec
) {
    const float groundY = -1.0;

    // ray is almost parallel to the ground
    if (abs(ray.direction.y) < 0.0001) {
        return false;
    }

    float t =
        (groundY - ray.origin.y) /
        ray.direction.y;

    // case 1: intersection lies behind the camera/ray origin
    // case 2: intersection is behind another object
    if (t <= tMin || t >= tMax) {
        return false;
    }

    rec.t = t;
    rec.position = rayAt(ray, t);

    vec3 outwardNormal = vec3(0.0, 1.0, 0.0);

    setFaceNormal(
        ray,
        outwardNormal,
        rec
    );

    rec.color = vec3(0.8);

    return true;
}

bool hitScene(
    Ray ray,
    out HitRecord closestHit
) {
    bool hitAnything = false;
    float closestT = 1.0 / 0.0; // set closest t to infinity

    for (uint i = 0; i < pc.objectCnt; ++i) {
        HitRecord temp;

        if (hitSphere(ray, spheres[i], 0.001, closestT, temp)) {
            hitAnything = true;
            closestT = temp.t;
            closestHit = temp;
        }
    }

    HitRecord groundHit;

    if (
        hitGround(
            ray,
            0.001, // tMin
            closestT, // tMax
            groundHit
        )
    ) {
        hitAnything = true;
        closestT = groundHit.t;
        closestHit = groundHit;
    }

    return hitAnything;
}

// diffuse lighting
bool nearZero(vec3 v) {
    const float epsilon = 1e-8;

    return
        abs(v.x) < epsilon &&
        abs(v.y) < epsilon &&
        abs(v.z) < epsilon;
}

/**
* generate a random vector inside the square in the range [-1, 1]
* accept only vectors that are in the unit sphere with radius 1
* i.e. squared length <= 1
*/
vec3 generateRandomInUnitSphere(inout uint rngState) {
    const float epsilon = 1e-16;

    while (true) {
        vec3 p = vec3(
            rnd(rngState),
            rnd(rngState),
            rnd(rngState)
        ) * 2.0 - 1.0;

        float lensq = dot(p, p);

        // reject small vectors to avoid floating point imprecision
        if (epsilon < lensq && lensq <= 1.0) {
            return p;
        }
    }
}

// return normalized accepted vector
vec3 generateRandomUnitVector(inout uint rngState) {
    return normalize(
        generateRandomInUnitSphere(rngState)
    );
}

/**
* takes a ray plus RNG state and follows the ray through the scene as it
* diffusively bounces, returns the RGB contribution of the whole path
*/
vec3 rayColor(
    Ray ray,
    inout uint rngState
) {
    vec3 throughput = vec3(1.0);

    // a single ray is allowed to bounce in the scene 8 times as the base
    const int MAX_BOUNCES = 8;

    for (int bounce = 0; bounce < MAX_BOUNCES; ++bounce) {
        HitRecord rec;

        if (hitScene(ray, rec)) {
            throughput *= rec.color;

            // adding the surface normal biases the random direction into hemisphere above surface
            // random unit vector is only between [-1, 1] and normal is either -1 or 1
            vec3 scatterDirection = rec.normal + generateRandomUnitVector(rngState);

            if (nearZero(scatterDirection)) {
                scatterDirection = rec.normal;
            }

            ray.origin = rec.position + rec.normal * 0.001;

            ray.direction = normalize(scatterDirection);
        }
        else {
            return throughput * skyColor(ray.direction);
        }
    }

    // ray has exceeded max. bounces without reaching the sky
    // discard all light contribution
    return vec3(0.0);
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);

    if (pixel.x >= size.x || pixel.y >= size.y) {
        return;
    }

    // Random jittered sampling for anti-aliasing
    // each pixel traces 8 rays instead of 1
    const uint SAMPLES_PER_PIXEL = 8;
    // random number generator state
    // a unique id per pixel is used as the seed
    uint pixelIdx = uint(pixel.y * size.x + pixel.x);
    uint rngState = tea(pixelIdx, 0u);

    // vec3 color = rayColor(ray);
    vec3 color = vec3(0.0);

    for (uint i = 0; i < SAMPLES_PER_PIXEL; ++i) {
        // rnd(rngState) produces random number from [0,1] resulting 
        // range is [-0.5, 0.5] which shows the offset from the original pixel
        vec2 jitter = vec2(rnd(rngState), rnd(rngState)) - 0.5;
        // pc.pixelDU is the equivalent world space distance of moving one pixel
        vec3 pixelPosition = 
            pc.pixelStart.xyz 
            + (float(pixel.x) + jitter.x) * pc.pixelDU.xyz 
            + (float(pixel.y) + jitter.y) * pc.pixelDV.xyz;

        Ray ray;
        ray.origin = pc.cameraPosition.xyz;
        ray.direction = normalize(pixelPosition - ray.origin);

        color += rayColor(ray, rngState);
    }

    color /= float(SAMPLES_PER_PIXEL);

    imageStore(outputImage, pixel, vec4(color, 1.0));
}